// ============================================================
//  app.js  —  visualization engine. Edit config.js, not this file.
// ============================================================
//
//  Two views over one join:
//    * a bivariate choropleth (states in true position)
//    * a scatterplot whose marks are the SAME state outlines
//
//  Both are drawn from one pre-projected TopoJSON, so a state's silhouette
//  in the scatter is geometrically identical to its shape on the map. That
//  identity is the whole conceit of the tool -- see README. (Hawaii is the
//  one exception: preprocess.js caps its size, so it carries less ink.)
//
//  The topology is ALREADY PROJECTED -- every coordinate is planar screen
//  space -- so d3.geoPath() is used with NO projection anywhere in this file,
//  and the viewBox comes from the topology's own bounds rather than from any
//  layout this file knows about.

import {
  TITLE, SUBTITLE, DATA_CREDIT, REPO_URL, REPO_LABEL,
  DATA_FILE, TOPOLOGY_FILE, SILHOUETTE_FILE, TOPOLOGY_OBJECT,
  TOPOLOGY_OUTLINE_OBJECT, TOPOLOGY_ID_PROP, TOPOLOGY_NAME_PROP,
  GEOGRAPHY_LABEL, FEATURE_ID_FIELD, FEATURE_NAME_FIELD, FEATURE_GROUP_FIELD,
  ID_PAD_WIDTH, VARIABLES, DEFAULT_VAR_X, DEFAULT_VAR_Y,
  DEFAULT_BIVARIATE_SCHEME, NULL_COLOR, NULL_HATCH_COLOR, SELECTION_COLOR,
  DEEMPHASIS_OPACITY,
  MARKER_SCALE, MARKER_RING_WIDTH, MARKER_RING_COLOR,
} from './config.js';

// ============================================================
//  BIVARIATE COLOR SCHEMES  (9 colors, row-major: yClass*3 + xClass)
// ============================================================
const BIVARIATE_SCHEMES = {
  DkBlue_DkRed: {
    label: 'Blue / Red',
    colors: ['#e8e8e8','#e4acac','#c85a5a',
             '#b0d5df','#ad9ea5','#985356',
             '#64acbe','#627f8c','#574249'],
  },
  DkViolet_DkGreen: {
    label: 'Violet / Green',
    colors: ['#e8e8e8','#b5c0da','#6c83b5',
             '#b8d6be','#90b2b3','#567994',
             '#73ae80','#5a9178','#2a5a5b'],
  },
  DkCyan_DkBrown: {
    label: 'Cyan / Brown',
    colors: ['#e8e8e8','#e4d9ac','#c8b35a',
             '#accea4','#a3b18a','#8c8c5e',
             '#5ac8c8','#5dbfa3','#3b7a7a'],
  },
  GrPink: {
    label: 'Green / Pink',
    colors: ['#f3f3f3','#f0d0d8','#e8a0b0',
             '#cce5cc','#c8c8c0','#c09090',
             '#8fbc8f','#8fa880','#7a7060'],
  },
  PurpleOrange: {
    label: 'Purple / Orange',
    colors: ['#f3f3f3','#f1d28a','#e8a830',
             '#cdc5e0','#c8b070','#b87820',
             '#9e6fbc','#907050','#704020'],
  },
  BlueTan: {
    label: 'Blue / Tan',
    colors: ['#f3f3f3','#e0d4b8','#c8b070',
             '#b8cce0','#a8b8b0','#909060',
             '#5090c8','#508090','#405050'],
  },
  None: { label: 'None (grey)', colors: Array(9).fill('#c8c8c8') },
};

const bivIndex = (xClass, yClass) => yClass * 3 + xClass;

// Features with no value are hatched rather than filled flat -- see
// buildPatterns() for why no solid colour can do this job here.
const NO_DATA_FILL = 'url(#noData)';

// ============================================================
//  STATE
// ============================================================
const state = {
  varX: DEFAULT_VAR_X,
  varY: DEFAULT_VAR_Y,
  scheme: DEFAULT_BIVARIATE_SCHEME,
  selectedIds: new Set(),
  hoverId: null,
};

let rows = [];        // joined records -- the data side; drives scatter + classes
let mapUnits = [];    // every geography in the topology, joined or not
let byId = new Map();
let borders, nation;  // topojson meshes
let mapView = null;   // viewBox derived from the topology's own bounds

// The brush extent is remembered in DATA units, together with the variables it
// was drawn against -- see the end of drawScatter().
let brushExtent = null;
let brushVars = null;

const varById = id => VARIABLES.find(v => v.id === id);
const padId = v => String(v).trim().padStart(ID_PAD_WIDTH, '0');
const $ = sel => document.querySelector(sel);

// Feature identity and display name, per config -- TopoJSON conventionally puts
// the key on the geometry, but plenty of files carry it in properties instead.
const idOf = f => String(TOPOLOGY_ID_PROP ? (f.properties || {})[TOPOLOGY_ID_PROP] : f.id);
const nameOf = f => (f.properties || {})[TOPOLOGY_NAME_PROP];

// Marker size as generated by preprocess.js, in the silhouettes' own units.
// Read from the silhouette file's meta block below rather than hardcoded, so
// changing MARKER_TARGET_AREA can't leave hit-testing quietly disagreeing with
// what is on screen.
let markerSide = Math.sqrt(400);

// All page copy comes from config.js, so adapting the tool never means editing
// markup. GEOGRAPHY_LABEL carries the running text: "Marks are county
// silhouettes", "Hover to trace an island to its mark".
const article = w => (/^[aeiou]/i.test(w) ? 'an' : 'a');
document.title = TITLE;
$('#titleText').textContent = TITLE;
$('#subtitleText').textContent = SUBTITLE;
$('#scatterNote').textContent =
  `Drag to brush a selection. Marks are ${GEOGRAPHY_LABEL} silhouettes, all equal area.`;
$('#mapNote').textContent =
  `Bivariate class by tercile on each variable. ` +
  `Hover to trace ${article(GEOGRAPHY_LABEL)} ${GEOGRAPHY_LABEL} to its mark.`;

// ============================================================
//  LOAD + JOIN
// ============================================================
Promise.all([
  d3.csv(DATA_FILE),
  d3.json(TOPOLOGY_FILE),
  d3.json(SILHOUETTE_FILE),
]).then(([csv, topo, silhouettes]) => {
  const object = topo.objects[TOPOLOGY_OBJECT];
  if (!object) {
    throw new Error(
      `TOPOLOGY_OBJECT "${TOPOLOGY_OBJECT}" is not in ${TOPOLOGY_FILE}. ` +
      `It holds: ${Object.keys(topo.objects).join(', ')}`
    );
  }
  const features = topojson.feature(topo, object).features;
  borders = topojson.mesh(topo, object, (a, b) => a !== b);
  const outline = TOPOLOGY_OUTLINE_OBJECT && topo.objects[TOPOLOGY_OUTLINE_OBJECT];
  nation = outline ? topojson.feature(topo, outline) : null;

  // preprocess.js writes { meta, shapes }; a file from before that format is
  // still read, since the shapes themselves never changed.
  const silMeta = silhouettes.meta || null;
  const shapes = silhouettes.shapes || silhouettes;
  if (silMeta) {
    markerSide = Math.sqrt(silMeta.targetArea);
    // A silhouette file left over from a previous geography is the failure this
    // catches: the shapes load, the ids look plausible, and the marks are
    // simply the wrong shapes.
    if (silMeta.source && silMeta.source !== TOPOLOGY_FILE) {
      console.warn(
        `[geometry] ${SILHOUETTE_FILE} was generated from ${silMeta.source}, ` +
        `but this page loads ${TOPOLOGY_FILE}. Re-run \`node preprocess.js\`.`
      );
    }
  } else {
    console.warn(
      `[geometry] ${SILHOUETTE_FILE} predates the meta block, so marker size is ` +
      `being assumed. Re-run \`node preprocess.js\`.`
    );
  }

  const geomById = new Map(features.map(f => [idOf(f), f]));

  // The pad is load-bearing: unpadded, every single-digit FIPS misses.
  const missing = [];
  rows = csv.map(r => {
    const id = padId(r[FEATURE_ID_FIELD]);
    const geom = geomById.get(id);
    const sil = shapes[id];
    if (!geom || !sil) { missing.push(r[FEATURE_NAME_FIELD]); return null; }
    const rec = {
      id,
      name: sil.name || r[FEATURE_NAME_FIELD],
      group: FEATURE_GROUP_FIELD ? r[FEATURE_GROUP_FIELD] : null,
      geom,
      d: sil.d,
      values: {},
    };
    for (const v of VARIABLES) {
      const raw = r[v.prop];
      const num = raw === '' || raw == null ? null : +raw;
      rec.values[v.id] = Number.isFinite(num) ? num : null;
    }
    return rec;
  }).filter(Boolean);

  byId = new Map(rows.map(r => [r.id, r]));

  // The map draws EVERY geography in the topology, not only the joined ones.
  // Binding just the data rows left an unmatched feature as a hole in the map
  // -- bare white inside the border mesh -- which reads as a rendering fault
  // rather than as missing data. Unmatched units carry no values, so they
  // classify as null and pick up the no-data hatch like any other gap.
  mapUnits = features.map(f => byId.get(idOf(f)) || {
    id: idOf(f),
    name: nameOf(f) || idOf(f),
    group: null,
    geom: f,
    values: {},
    unmatched: true,
  });

  // The viewBox comes from the topology's own bounds rather than a hardcoded
  // 975x610. us-atlas' Albers layout actually starts at x = -57.7 -- the
  // western Aleutians sit left of the origin -- so a 0-origin box quietly
  // clipped them off Alaska. Any other topology has different extents again.
  const [[bx0, by0], [bx1, by1]] =
    d3.geoPath().bounds({ type: 'FeatureCollection', features });
  const gap = Math.max(bx1 - bx0, by1 - by0) * 0.005;
  mapView = [bx0 - gap, by0 - gap, (bx1 - bx0) + gap * 2, (by1 - by0) + gap * 2];

  // Join diagnostics stay available but off the page: a clean join is the
  // normal case and doesn't need announcing. A broken one is usually the
  // FIPS zero-padding (see ID_PAD_WIDTH), which drops exactly the
  // single-digit states and otherwise looks like success.
  const unjoined = features.filter(f => !byId.has(idOf(f)));
  if (missing.length || unjoined.length) {
    console.warn(
      `[join] ${rows.length} of ${csv.length} ${GEOGRAPHY_LABEL}s matched from ${DATA_FILE}.`,
      missing.length ? `\n  ${missing.length} data row(s) without geometry: ${missing.join(', ')}` : '',
      unjoined.length ? `\n  ${unjoined.length} geometr(ies) without data: ${unjoined.map(f => nameOf(f) || idOf(f)).join(', ')}` : ''
    );
  }

  // Variable diagnostics. A variable whose `prop` doesn't match the CSV header
  // -- a typo, or a column renamed upstream -- yields nothing but nulls, and
  // every downstream symptom of that (empty axes, a blank legend, a wholly
  // hatched map) points away from the cause. Name it here instead.
  const header = new Set(csv.columns || []);
  const absent = VARIABLES.filter(v => !header.has(v.prop));
  const blank = VARIABLES.filter(
    v => header.has(v.prop) && !rows.some(r => r.values[v.id] != null)
  );
  if (absent.length) {
    console.warn(
      `[data] ${absent.length} variable(s) name a column that is not in ${DATA_FILE}: ` +
      absent.map(v => `"${v.prop}" (${v.label})`).join(', ')
    );
  }
  if (blank.length) {
    console.warn(
      `[data] ${blank.length} variable(s) have a column but no numeric values in it ` +
      `(blank, or non-numeric text such as "1,234"): ` +
      blank.map(v => `"${v.prop}" (${v.label})`).join(', ')
    );
  }

  buildPatterns();
  buildFooter();
  buildControls();
  render();
});

// ============================================================
//  CLASSIFICATION — terciles per variable
// ============================================================
function terciles(varId) {
  const vals = rows.map(r => r.values[varId]).filter(v => v != null).sort(d3.ascending);
  // Fewer than three values cannot define two breaks. d3.quantile returns
  // undefined on an empty array, and that undefined used to travel as far as
  // vx.fmt() in the legend and throw mid-render -- leaving a half-drawn page
  // whose likeliest cause (a mistyped `prop` in config.js) appeared nowhere in
  // the error. Returning null classifies every feature as no-data instead,
  // which is both true and visible.
  if (vals.length < 3) return null;
  return [d3.quantile(vals, 1 / 3), d3.quantile(vals, 2 / 3)];
}

function classOf(value, breaks) {
  if (value == null || breaks == null) return null;
  return value <= breaks[0] ? 0 : value <= breaks[1] ? 1 : 2;
}

function colorFor(rec, bx, by) {
  const cx = classOf(rec.values[state.varX], bx);
  const cy = classOf(rec.values[state.varY], by);
  if (cx == null || cy == null) return NO_DATA_FILL;
  return BIVARIATE_SCHEMES[state.scheme].colors[bivIndex(cx, cy)];
}

// ============================================================
//  NO-DATA HATCH
// ============================================================
// A flat grey cannot mark "no data" on a bivariate map: the lowest cell of
// every scheme here IS a pale grey (#e8e8e8 or #f3f3f3), so a grey null is
// indistinguishable from a genuine low-low value -- and on this dataset a
// third of the map sits in that cell. A hatch is the cartographic convention
// and is the one fill no class can imitate.
//
// It lives in its own SVG because the map and the scatter each clear
// themselves on every render. url(#noData) resolves document-wide, so a single
// definition serves both views and the legend key.
function buildPatterns() {
  const svg = d3.select('#patterns');
  svg.selectAll('*').remove();
  const p = svg.append('defs').append('pattern')
    .attr('id', 'noData')
    .attr('patternUnits', 'userSpaceOnUse')
    .attr('width', 6).attr('height', 6)
    .attr('patternTransform', 'rotate(45)');
  p.append('rect').attr('width', 6).attr('height', 6).attr('fill', NULL_COLOR);
  p.append('line')
    .attr('x1', 0).attr('y1', 0).attr('x2', 0).attr('y2', 6)
    .attr('stroke', NULL_HATCH_COLOR).attr('stroke-width', 2);
}

// The table's swatch is an HTML span and cannot reference an SVG paint server,
// so the same hatch is restated once as a CSS gradient.
const NO_DATA_SWATCH =
  `repeating-linear-gradient(45deg, ${NULL_COLOR} 0 3px, ${NULL_HATCH_COLOR} 3px 5px)`;

// ============================================================
//  FOOTER
// ============================================================
// Built as nodes rather than an HTML string: these values come from
// config.js, and the repo link should never be assembled by concatenation.
function buildFooter() {
  const foot = $('#pageFoot');
  foot.textContent = '';
  if (DATA_CREDIT) foot.append(document.createTextNode(`Data: ${DATA_CREDIT}. `));
  if (REPO_URL) {
    foot.append(document.createTextNode('Source code, method notes and full citations: '));
    const a = document.createElement('a');
    a.href = REPO_URL;
    a.textContent = REPO_LABEL || REPO_URL;
    a.rel = 'noopener';
    a.target = '_blank';
    foot.append(a);
    foot.append(document.createTextNode('.'));
  }
}

// ============================================================
//  CONTROLS
// ============================================================
function buildControls() {
  const fill = (sel, selected) => {
    sel.innerHTML = '';
    for (const v of VARIABLES) {
      const o = document.createElement('option');
      o.value = v.id; o.textContent = v.label;
      if (v.id === selected) o.selected = true;
      sel.appendChild(o);
    }
  };
  fill($('#varX'), state.varX);
  fill($('#varY'), state.varY);

  const schemeSel = $('#scheme');
  schemeSel.innerHTML = '';
  for (const [id, s] of Object.entries(BIVARIATE_SCHEMES)) {
    const o = document.createElement('option');
    o.value = id; o.textContent = s.label;
    if (id === state.scheme) o.selected = true;
    schemeSel.appendChild(o);
  }

  $('#varX').addEventListener('change', e => { state.varX = e.target.value; render(); });
  $('#varY').addEventListener('change', e => { state.varY = e.target.value; render(); });
  schemeSel.addEventListener('change', e => { state.scheme = e.target.value; render(); });
  $('#clearBtn').addEventListener('click', () => {
    state.selectedIds.clear();
    brushExtent = brushVars = null;
    render();
  });
  $('#tableBtn').addEventListener('click', e => {
    const wrap = $('#tableWrap');
    const show = wrap.hidden;
    wrap.hidden = !show;
    e.target.textContent = show ? 'Hide table' : 'Show table';
    e.target.setAttribute('aria-expanded', String(show));
  });
}

// ============================================================
//  RENDER
// ============================================================
function render() {
  const vx = varById(state.varX);
  const vy = varById(state.varY);
  const bx = terciles(state.varX);
  const by = terciles(state.varY);

  $('#scatterTitle').textContent = `${vy.label} vs ${vx.label}`;
  $('#mapTitle').textContent = `${vy.label} × ${vx.label}`;

  // The legend shows a no-data key only when something actually lacks data.
  const hasNoData = mapUnits.some(
    r => classOf(r.values[state.varX], bx) == null ||
         classOf(r.values[state.varY], by) == null
  );

  drawScatter(vx, vy, bx, by);
  drawMap(bx, by);
  drawLegend(vx, vy, bx, by, hasNoData);
  drawTable(vx, vy, bx, by);
}

// ---- scatterplot -----------------------------------------------------
function drawScatter(vx, vy, bx, by) {
  const W = 640, H = 560;
  const m = { top: 14, right: 18, bottom: 46, left: 56 };
  const iw = W - m.left - m.right;
  const ih = H - m.top - m.bottom;

  const svg = d3.select('#scatter')
    .attr('viewBox', `0 0 ${W} ${H}`)
    .attr('aria-label', `${vy.label} versus ${vx.label}`);
  svg.selectAll('*').remove();

  const xs = rows.map(r => r.values[state.varX]).filter(v => v != null);
  const ys = rows.map(r => r.values[state.varY]).filter(v => v != null);

  // When both axes carry the same unit, share one domain so the 1:1 line
  // is a true 45 degrees and "above the line" means "gained" honestly.
  // Both halves of this test matter. Two variables that simply never declared
  // a `unit` are not "the same unit" -- without the null check,
  // `undefined === undefined` handed any such pair a shared domain, a 1:1 line
  // labelled "no change", and a change figure in the tooltip, none of which
  // meant anything.
  const sameUnit = vx.unit != null && vx.unit === vy.unit;
  const pad = 0.06;
  const span = (arr) => {
    const [lo, hi] = d3.extent(arr);
    if (lo == null) return [0, 1];      // nothing to plot; keep the axes finite
    const g = (hi - lo) * pad || 1;     // a single distinct value has no span
    return [lo - g, hi + g];
  };
  const domX = sameUnit ? span(xs.concat(ys)) : span(xs);
  const domY = sameUnit ? domX : span(ys);

  const x = d3.scaleLinear().domain(domX).range([0, iw]).nice();
  const y = d3.scaleLinear().domain(domY).range([ih, 0]).nice();

  const g = svg.append('g').attr('transform', `translate(${m.left},${m.top})`);

  g.append('g').attr('class', 'grid')
    .selectAll('line').data(y.ticks(6)).join('line')
    .attr('x1', 0).attr('x2', iw).attr('y1', y).attr('y2', y);
  g.append('g').attr('class', 'grid')
    .selectAll('line').data(x.ticks(6)).join('line')
    .attr('y1', 0).attr('y2', ih).attr('x1', x).attr('x2', x);

  // 1:1 reference line — only meaningful on a shared domain.
  if (sameUnit) {
    const lo = Math.max(x.domain()[0], y.domain()[0]);
    const hi = Math.min(x.domain()[1], y.domain()[1]);
    g.append('line').attr('class', 'refline')
      .attr('x1', x(lo)).attr('y1', y(lo))
      .attr('x2', x(hi)).attr('y2', y(hi));
    // Sits below the line, not across it.
    g.append('text').attr('class', 'refline-label')
      .attr('x', x(hi) - 8).attr('y', y(hi) + 22).attr('text-anchor', 'end')
      .text('no change (1:1)');
  }

  g.append('g').attr('class', 'axis')
    .attr('transform', `translate(0,${ih})`).call(d3.axisBottom(x).ticks(6));
  g.append('g').attr('class', 'axis').call(d3.axisLeft(y).ticks(6));

  g.append('text').attr('class', 'axis-title')
    .attr('x', iw / 2).attr('y', ih + 38).attr('text-anchor', 'middle')
    .text(vx.label);
  g.append('text').attr('class', 'axis-title')
    .attr('transform', `rotate(-90)`)
    .attr('x', -ih / 2).attr('y', -42).attr('text-anchor', 'middle')
    .text(vy.label);

  const marksG = g.append('g');
  const hasSel = state.selectedIds.size > 0;

  const plotted = rows.filter(
    r => r.values[state.varX] != null && r.values[state.varY] != null
  );

  marksG.selectAll('path.mark')
    .data(plotted, d => d.id)
    .join('path')
    .attr('class', d => 'mark' + (hasSel && !state.selectedIds.has(d.id) ? ' dim' : ''))
    .attr('d', d => d.d)
    .attr('transform', d =>
      `translate(${x(d.values[state.varX])},${y(d.values[state.varY])}) scale(${MARKER_SCALE})`)
    .attr('fill', d => colorFor(d, bx, by))
    .attr('stroke', MARKER_RING_COLOR)
    .attr('stroke-width', MARKER_RING_WIDTH / MARKER_SCALE)
    .attr('paint-order', 'stroke')
    .attr('vector-effect', 'non-scaling-stroke')
    .attr('pointer-events', 'none');   // hit-testing happens on the brush layer

  // The brush must sit ABOVE the marks or a drag starting on a silhouette
  // would never begin a selection -- and with 51 marks this size, most of
  // the plot is covered by one. So the marks are inert and the brush
  // overlay resolves hover itself, by nearest anchor within HIT_RADIUS.
  // Anchors are area-weighted centroids, which is also what the marks are
  // positioned by, so "nearest anchor" and "the mark you are pointing at"
  // agree except in dense overlaps -- where no rule can do better.
  const brushG = g.append('g').attr('class', 'brush');
  // Slightly wider than the marker itself, so pointing just off a shape still
  // finds it. Derived from what preprocess.js actually generated.
  const HIT_RADIUS = markerSide * 1.1 * MARKER_SCALE;
  const tree = d3.quadtree()
    .x(d => x(d.values[state.varX]))
    .y(d => y(d.values[state.varY]))
    .addAll(plotted);

  const brush = d3.brush()
    .extent([[0, 0], [iw, ih]])
    .on('end', ev => {
      if (!ev.sourceEvent) return;
      if (!ev.selection) {
        brushExtent = brushVars = null;
        state.selectedIds.clear(); render(); return;
      }
      const [[x0, y0], [x1, y1]] = ev.selection;
      state.selectedIds = new Set(
        plotted.filter(d => {
          const px = x(d.values[state.varX]);
          const py = y(d.values[state.varY]);
          return px >= x0 && px <= x1 && py >= y0 && py <= y1;
        }).map(d => d.id)
      );
      // Kept in DATA units, not pixels, so it survives the rebuild below and
      // still means the same thing after a scheme change or a resize.
      brushExtent = [[x.invert(x0), y.invert(y1)], [x.invert(x1), y.invert(y0)]];
      brushVars = [state.varX, state.varY];
      render();
    });
  brushG.call(brush);

  // Put the rectangle back. drawScatter clears the SVG on every render, so
  // releasing the mouse used to erase the brush along with everything else:
  // the selection survived, the handles did not, and adjusting a selection
  // meant drawing it again from scratch. A change of VARIABLE retires the
  // extent rather than re-projecting it -- the same data window on new axes is
  // a different question from the one the reader asked. brush.move fires with
  // no sourceEvent, so the handler above ignores it.
  if (brushExtent && brushVars &&
      brushVars[0] === state.varX && brushVars[1] === state.varY) {
    const [[dx0, dy0], [dx1, dy1]] = brushExtent;
    brushG.call(brush.move, [[x(dx0), y(dy1)], [x(dx1), y(dy0)]]);
  } else {
    brushExtent = brushVars = null;
  }
  brushG.selectAll('.overlay')
    .attr('cursor', 'crosshair')
    .on('mousemove.hover', ev => {
      const [mx, my] = d3.pointer(ev);
      const hit = tree.find(mx, my, HIT_RADIUS);
      if (hit) {
        if (hit.id !== state.hoverId) { state.hoverId = hit.id; highlight(); }
        showTip(ev, hit);
      } else if (state.hoverId) {
        state.hoverId = null; highlight(); hideTip();
      } else {
        hideTip();
      }
    })
    .on('mouseleave.hover', () => {
      state.hoverId = null; highlight(); hideTip();
    });
}

// ---- choropleth ------------------------------------------------------
function drawMap(bx, by) {
  const svg = d3.select('#map').attr('viewBox', mapView.join(' '));
  svg.selectAll('*').remove();

  // No projection: the topology is already in this coordinate space.
  const path = d3.geoPath();
  const hasSel = state.selectedIds.size > 0;

  svg.append('g').selectAll('path.map-state')
    .data(mapUnits, d => d.id)
    .join('path')
    .attr('class', d => 'map-state' + (hasSel && !state.selectedIds.has(d.id) ? ' dim' : ''))
    .attr('d', d => path(d.geom))
    .attr('fill', d => colorFor(d, bx, by))
    .on('mouseenter', (ev, d) => { state.hoverId = d.id; highlight(); showTip(ev, d); })
    .on('mousemove', moveTip)
    .on('mouseleave', () => { state.hoverId = null; highlight(); hideTip(); })
    .on('click', (ev, d) => {
      if (d.unmatched) return;   // no data row behind it, so nothing to select
      if (state.selectedIds.has(d.id)) state.selectedIds.delete(d.id);
      else state.selectedIds.add(d.id);
      render();
    });

  if (borders) svg.append('path').attr('class', 'state-border').attr('d', path(borders));
  if (nation) svg.append('path').attr('class', 'nation-border').attr('d', path(nation));

  // Selected states get an outline that survives the de-emphasis wash.
  svg.append('g').selectAll('path.sel')
    .data(mapUnits.filter(d => state.selectedIds.has(d.id)), d => d.id)
    .join('path')
    .attr('class', 'sel')
    .attr('d', d => path(d.geom))
    .attr('fill', 'none')
    .attr('stroke', SELECTION_COLOR)
    .attr('stroke-width', 1.6)
    .attr('pointer-events', 'none');

  svg.style('--dim', DEEMPHASIS_OPACITY);
  d3.select('#scatter').style('--dim', DEEMPHASIS_OPACITY);
  highlight();
}

// Cross-view emphasis: hovering either view outlines the same state in both.
function highlight() {
  d3.selectAll('#scatter path.mark, #map path.map-state')
    .classed('hl', d => d && d.id === state.hoverId)
    .filter(d => d && d.id === state.hoverId)
    .raise();
}

// ---- legend ----------------------------------------------------------
// Names the variables and shows the tercile break values, so the key can be
// read without consulting the controls. Truncation keeps a long variable
// label from stretching the panel.
function drawLegend(vx, vy, bx, by, hasNoData) {
  const S = 26, gap = 2;
  const size = S * 3 + gap * 2;
  const padL = 56, padT = 6, padR = 8;
  const padB = hasNoData ? 64 : 48;   // room for the no-data key when needed
  const W = padL + size + padR;
  const H = padT + size + padB;

  const svg = d3.select('#legendSvg')
    .attr('width', W).attr('height', H).attr('viewBox', `0 0 ${W} ${H}`);
  svg.selectAll('*').remove();

  const colors = BIVARIATE_SCHEMES[state.scheme].colors;
  const g = svg.append('g').attr('transform', `translate(${padL},${padT})`);

  for (let r = 0; r < 3; r++) {
    for (let c = 0; c < 3; c++) {
      // Row 0 is the TOP of the key = the HIGH class on Y.
      g.append('rect')
        .attr('x', c * (S + gap)).attr('y', r * (S + gap))
        .attr('width', S).attr('height', S)
        .attr('fill', colors[bivIndex(c, 2 - r)])
        .attr('stroke', 'rgba(0,0,0,.12)');
    }
  }

  // Wrap rather than truncate. A clipped label reading "…share, 1976–20."
  // looks like a real but WRONG year range, which is worse than no label.
  const wrap = (s, maxChars, maxLines = 2) => {
    const lines = [];
    let cur = '';
    for (const word of s.split(/\s+/)) {
      if (!cur) cur = word;
      else if ((cur + ' ' + word).length <= maxChars) cur += ' ' + word;
      else { lines.push(cur); cur = word; }
    }
    if (cur) lines.push(cur);
    if (lines.length > maxLines) {
      const kept = lines.slice(0, maxLines);
      kept[maxLines - 1] = kept[maxLines - 1].replace(/.{1}$/, '') + '…';
      return kept;
    }
    return lines;
  };

  const multiline = (sel, lines, x, y, dy = 10) =>
    lines.forEach((ln, i) =>
      sel.append('tspan').attr('x', x).attr('y', y + i * dy).text(ln));

  const tick = { 'font-size': 8, fill: '#898781' };

  // Break values at the class boundaries. Absent when the variable had too few
  // values to break on -- see terciles().
  if (bx) bx.forEach((b, i) => {
    g.append('text')
      .attr('x', (i + 1) * (S + gap) - gap / 2).attr('y', size + 11)
      .attr('text-anchor', 'middle').attr('font-size', 8).attr('fill', tick.fill)
      .text(vx.fmt(b));
  });
  if (by) by.forEach((b, i) => {
    g.append('text')
      .attr('x', -5).attr('y', size - (i + 1) * (S + gap) + gap / 2 + 3)
      .attr('text-anchor', 'end').attr('font-size', 8).attr('fill', tick.fill)
      .text(vy.fmt(b));
  });

  const xLab = g.append('text')
    .attr('text-anchor', 'middle')
    .attr('font-size', 9).attr('font-weight', 600).attr('fill', '#52514e');
  multiline(xLab, wrap(vx.label + ' →', 24), size / 2, size + 25);

  const yLab = g.append('text')
    .attr('transform', 'rotate(-90)')
    .attr('text-anchor', 'middle')
    .attr('font-size', 9).attr('font-weight', 600).attr('fill', '#52514e');
  multiline(yLab, wrap(vy.label + ' →', 24), -size / 2, -42);

  if (hasNoData) {
    g.append('rect')
      .attr('x', 0).attr('y', size + 44)
      .attr('width', 11).attr('height', 11)
      .attr('fill', NO_DATA_FILL).attr('stroke', 'rgba(0,0,0,.12)');
    g.append('text')
      .attr('x', 16).attr('y', size + 53)
      .attr('font-size', 9).attr('fill', '#52514e')
      .text('no data');
  }
}

// ---- table view (relief channel; identity never color-alone) ----------
function drawTable(vx, vy, bx, by) {
  $('#thX').textContent = vx.label;
  $('#thY').textContent = vy.label;
  const names = ['low', 'mid', 'high'];
  const tbody = $('#dataTable tbody');
  tbody.innerHTML = '';

  // mapUnits, not rows: a geography with no data row still appears on the map,
  // so it has to be findable here as well -- this table is the map's relief
  // channel. With a clean join the two lists are identical.
  const sorted = [...mapUnits].sort((a, b) => d3.ascending(a.name, b.name));
  for (const r of sorted) {
    const cx = classOf(r.values[state.varX], bx);
    const cy = classOf(r.values[state.varY], by);
    const tr = document.createElement('tr');
    const label = cx == null || cy == null
      ? 'no data'
      : `X ${names[cx]} · Y ${names[cy]}`;
    const swatch = cx == null || cy == null ? NO_DATA_SWATCH : colorFor(r, bx, by);
    tr.innerHTML =
      `<td>${r.name}${r.group ? ` <span style="color:#898781">(${r.group})</span>` : ''}</td>` +
      `<td class="num">${r.values[state.varX] == null ? '—' : vx.fmt(r.values[state.varX])}</td>` +
      `<td class="num">${r.values[state.varY] == null ? '—' : vy.fmt(r.values[state.varY])}</td>` +
      `<td><span class="swatch" style="background:${swatch}"></span>${label}</td>`;
    tbody.appendChild(tr);
  }
}

// ---- tooltip ---------------------------------------------------------
function showTip(ev, d) {
  const vx = varById(state.varX), vy = varById(state.varY);
  const fx = d.values[state.varX], fy = d.values[state.varY];
  // Formatted by the variable's own fmt() rather than a hardcoded toFixed(1):
  // the change between two dollar figures or two counts is not a percentage.
  const sameUnit = vx.unit != null && vx.unit === vy.unit;
  const diff = sameUnit && fx != null && fy != null ? fy - fx : null;
  const delta = diff == null
    ? ''
    : `<div class="k">change: ${diff >= 0 ? '+' : '−'}${vy.fmt(Math.abs(diff))}</div>`;
  $('#tip').innerHTML =
    `<b>${d.name}</b>${d.group ? ` <span class="k">${d.group}</span>` : ''}` +
    `<div><span class="k">${vx.label}:</span> ${fx == null ? '—' : vx.fmt(fx)}</div>` +
    `<div><span class="k">${vy.label}:</span> ${fy == null ? '—' : vy.fmt(fy)}</div>` +
    delta;
  $('#tip').style.opacity = 1;
  moveTip(ev);
}
function moveTip(ev) {
  const t = $('#tip');
  const ox = 14, oy = 14;
  let left = ev.clientX + ox, top = ev.clientY + oy;
  const r = t.getBoundingClientRect();
  if (left + r.width > window.innerWidth) left = ev.clientX - r.width - ox;
  if (top + r.height > window.innerHeight) top = ev.clientY - r.height - oy;
  t.style.left = left + 'px';
  t.style.top = top + 'px';
}
function hideTip() { $('#tip').style.opacity = 0; }
